name: Publish documentation
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  publish-documentation:
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Publish docs api to repo
        run: |
          npm ci
          npm run doc
          git status
          git add docs/api/md
          git commit -am "updated api docs"
          git fetch origin main
          git push origin main
      - run: npm ci
      - run: npm run doc:publish
      - id: upload-documentation
        name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs/api/html
      - id: deployment
        name: Deploy documentation to GitHub Pages
        uses: actions/deploy-pages@v2
