name: Publish documentation
on:
  push:
    branches:
      - main

jobs:
  publish-documentation:
    permissions:
      id-token: write
      pages: write
      contents: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Generate HTML documentation
        run: |
          npm ci
          npm run doc:publish
      - id: upload-documentation
        name: Upload documentation to Pages
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: docs/api/html
      - id: deployment
        name: Deploy documentation to GitHub Pages
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
