name: Check Lockfile
on: pull_request
jobs:
  lockfile_version:
    name: Lockfile version check
    runs-on: ubuntu-latest
    steps:
      - name: Check out a copy of the repo
        uses: actions/checkout@v4
      - name: Check package-lock.json version has not been changed
        uses: mansona/npm-lockfile-version@v1
        with:
          version: 3
  lockfile_changes:
    name: Lockfile changes check
    runs-on: ubuntu-latest
    steps:
      - name: Check out a copy of the repo
        uses: actions/checkout@v4
      - name: NPM Lockfile Changes
        uses: codepunkt/npm-lockfile-changes@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
